Update action.yml

diff --git a/actions/get-project-info/action.yml b/actions/get-project-info/action.yml
--- a/actions/get-project-info/action.yml
+++ b/actions/get-project-info/action.yml
@@ -40,7 +40,7 @@ runs:
       if: ${{ inputs.skip-validation != 'true' }}
       shell: bash
       run: |
-        echo "${BUILD_VERSION}" | grep -E '^[0-9]+\.[0-9]+(\.[0-9]+)?$' || (>&2 echo "Invalid version number format, found ${BUILD_VERSION}"; exit -1)
+        echo "${BUILD_VERSION}" | grep -E '^[0-9]+\.[0-9]+(\.[0-9]+)?$' > /dev/null || (>&2 echo "Invalid version number format, found ${BUILD_VERSION}"; exit -1)
         
         [ -z "${{ inputs.expected-version }}" ] || [ "${{ inputs.expected-version }}" == "${BUILD_VERSION}" ] || (>&2 echo "Project version does not match expected value, found ${BUILD_VERSION} but expected ${{ inputs.expected-version }}"; exit -1)
 
